import type { DragonSynergyProfile } from './types';

export const simpleSynergyProfiles = [
  {
    dragonId: 'daemoros',
    dragonName: 'Daemoros',
    outputs: [
      {
        id: 'daemoros-instill-fear-panic',
        tag: 'status:panic',
        abilityId: 'daemoros-instill-fear',
        abilityName: 'Instill Fear',
        description: 'applies Panic',
        unlock: { minimumStarRank: 2 },
        friendlyScope: 'formation',
        confidence: 'verified',
      },
    ],
    supports: [],
    benefitsFrom: [],
    positionClaims: [],
  },
  {
    dragonId: 'shadowsong',
    dragonName: 'Shadowsong',
    outputs: [],
    supports: [],
    benefitsFrom: [
      {
        id: 'shadowsong-breath-of-fire-panic-payoff',
        tag: 'status:panic',
        abilityId: 'shadowsong-breath-of-fire',
        abilityName: 'Breath of Fire',
        description: "Panic improves Breath of Fire's damage",
        friendlyScope: 'formation',
        confidence: 'verified',
      },
    ],
    positionClaims: [],
  },
  {
    dragonId: 'syrax',
    dragonName: 'Syrax',
    outputs: [
      {
        id: 'syrax-blazing-fury-first-strike',
        tag: 'status:first-strike',
        abilityId: 'syrax-blazing-fury',
        abilityName: 'Blazing Fury',
        description: 'grants First-Strike to a teammate',
        friendlyScope: 'formation',
        confidence: 'verified',
      },
    ],
    supports: [
      {
        id: 'syrax-blazing-fury-fire-support',
        tag: 'damage:fire',
        abilityId: 'syrax-blazing-fury',
        abilityName: 'Blazing Fury',
        description: 'improves allied Fire Damage',
        friendlyScope: 'formation',
        confidence: 'verified',
      },
    ],
    benefitsFrom: [],
    positionClaims: [],
  },
  {
    dragonId: 'caraxes',
    dragonName: 'Caraxes',
    outputs: [
      {
        id: 'caraxes-infernal-burst-fire',
        tag: 'damage:fire',
        abilityId: 'caraxes-infernal-burst',
        abilityName: 'Infernal Burst',
        description: 'deals Fire Damage',
        confidence: 'verified',
      },
    ],
    supports: [],
    benefitsFrom: [
      {
        id: 'caraxes-infernal-burst-first-strike-payoff',
        tag: 'status:first-strike',
        abilityId: 'caraxes-infernal-burst',
        abilityName: 'Infernal Burst',
        description: 'First-Strike improves Infernal Burst',
        friendlyScope: 'formation',
        confidence: 'verified',
      },
    ],
    positionClaims: [
      {
        id: 'caraxes-hunters-wrath-vanguard',
        abilityId: 'caraxes-hunters-wrath',
        abilityName: "Hunter's Wrath",
        requiredPosition: 'vanguard',
        unlock: { minimumDragonLevel: 16 },
        description: "Hunter's Wrath is a meaningful Vanguard trait",
        confidence: 'verified',
      },
    ],
  },
  {
    dragonId: 'malachite',
    dragonName: 'Malachite',
    outputs: [
      {
        id: 'malachite-wardens-rally-recovery',
        tag: 'effect:recovery',
        abilityId: 'malachite-wardens-rally',
        abilityName: "Warden's Rally",
        description: 'provides Recovery',
        friendlyScope: 'formation',
        confidence: 'verified',
      },
      {
        id: 'malachite-lightning-strike-first-strike',
        tag: 'status:first-strike',
        abilityId: 'malachite-lightning-strike',
        abilityName: 'Lightning Strike',
        description: 'grants First-Strike to an adjacent other ally',
        unlock: { minimumStarRank: 10 },
        friendlyScope: 'adjacent',
        confidence: 'verified',
      },
    ],
    supports: [],
    benefitsFrom: [],
    positionClaims: [],
  },
  {
    dragonId: 'sheepstealer',
    dragonName: 'Sheepstealer',
    outputs: [],
    supports: [],
    benefitsFrom: [
      {
        id: 'sheepstealer-hunters-cunning-recovery-payoff',
        tag: 'effect:recovery',
        abilityId: 'sheepstealer-hunters-cunning',
        abilityName: "Hunter's Cunning",
        description: "Hunter's Cunning improves incoming Recovery",
        unlock: { minimumDragonLevel: 16 },
        requiredSelfPosition: 'vanguard',
        friendlyScope: 'formation',
        confidence: 'verified',
      },
    ],
    positionClaims: [
      {
        id: 'sheepstealer-hunters-cunning-vanguard',
        abilityId: 'sheepstealer-hunters-cunning',
        abilityName: "Hunter's Cunning",
        requiredPosition: 'vanguard',
        unlock: { minimumDragonLevel: 16 },
        description: "Hunter's Cunning is a meaningful Vanguard trait",
        confidence: 'verified',
      },
    ],
  },
] satisfies DragonSynergyProfile[];
